# DO NOT EDIT this file. It is set up in such a way that if you make any edits,
# the test cases may change resulting in a broken local autograder.

# Imports
import sys, os, pdb
from test import Test

# Append paths and run
sys.path.append("MCQ")
print(sys.path)
import mcq


############################################################################################
################################   Section 1 - MCQ    ######################################
############################################################################################


class MCQTest(Test):
    def __init__(self):
        pass

    def test_mutiple_choice(self):
        scores = [0, 0, 0, 0, 0]

        ref = ["b", "c", "b", "b", "a"]
        ans_1 = mcq.question_1()
        ans_2 = mcq.question_2()
        ans_3 = mcq.question_3()
        ans_4 = mcq.question_4()
        ans_5 = mcq.question_5()
        ans = [ans_1, ans_2, ans_3, ans_4, ans_5]

        for i in range(len(ref)):
            if ref[i] == ans[i]:
                scores[i] = 1

        return scores

    def run_test(self):
        # Test MCQs
        self.print_name("Section 1 - Multiple Choice Questions")
        scores = self.test_mutiple_choice()
        a, b, c, d, e = scores
        all_correct = a and b and c and d and e
        self.print_outcome("Multiple Choice Questions", all_correct)
        if all_correct == False:
            self.print_failure("Multiple Choice Questions")
            return False, sum(scores)

        return True
